# Generated by Django 3.0.6 on 2020-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_followers_+', to='accounts.Profile'),
        ),
    ]
