# Generated by Django 3.0.6 on 2020-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200509_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to=''),
        ),
    ]
